# coding=utf-8
# src_do_thi.py
import re, os, sys, csv, codecs, time
from datetime import datetime, timedelta
from urllib.request import urlopen
import math, argparse, subprocess, signal, shutil, errno, unicodedata, webbrowser
from fractions import Fraction
from decimal import Decimal
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from def_calculation import *
from src_reg import *
from def_bbt import *
from def_id import *
from def_convert import *
from def_ban_quyen import *

class Draw_Graph(QWidget):

    def __init__(self, parent=None):
        QWidget.__init__(self, parent)
        self.setLayout(QGridLayout())
        self.group0 = QGroupBox('Các tùy biến trong vẽ hình')
        self.group0.vbox = QVBoxLayout()
        self.group0.check1 = QRadioButton('Auto (Thể hiện ý đồ tác giả khi vẽ hình, thầy cô chọn Manual để tự tùy biến)')
        self.group0.check1.setCheckable(True)
        self.group0.check1.setChecked(True)
        self.group0.check1.toggled.connect(self.Auto_Check)
        self.group0.check2 = QGroupBox('Manual')
        self.group0.check2.setFlat(True)
        self.group0.check2.setCheckable(True)
        self.group0.check2.setChecked(False)
        self.group0.check2.toggled.connect(self.Manual_Check)
        self.group0.hbox = QHBoxLayout()
        self.group0.hbox1 = QHBoxLayout()
        self.group0.hbox2 = QHBoxLayout()
        self.group0.labela = QLabel()
        self.group0.labela.setText('Trục hoành')
        self.group0.labela.setMaximumWidth(60)
        self.group0.linea = QLineEdit()
        self.group0.linea.setText('-3')
        self.group0.linea.setMaximumWidth(20)
        self.group0.labelb = QLabel()
        self.group0.labelb.setText('<x<')
        self.group0.labelb.setMaximumWidth(20)
        self.group0.lineb = QLineEdit()
        self.group0.lineb.setText('3')
        self.group0.lineb.setMaximumWidth(20)
        self.group0.hbox1.addWidget(self.group0.labela)
        self.group0.hbox1.addWidget(self.group0.linea)
        self.group0.hbox1.addWidget(self.group0.labelb)
        self.group0.hbox1.addWidget(self.group0.lineb)
        self.group0.labelc = QLabel()
        self.group0.labelc.setText('Trục tung ')
        self.group0.labelc.setMaximumWidth(70)
        self.group0.linec = QLineEdit()
        self.group0.linec.setText('-3')
        self.group0.linec.setMaximumWidth(20)
        self.group0.labeld = QLabel()
        self.group0.labeld.setText('<y<')
        self.group0.labeld.setMaximumWidth(20)
        self.group0.lined = QLineEdit()
        self.group0.lined.setText('3')
        self.group0.lined.setMaximumWidth(20)
        self.group0.hbox2.addWidget(self.group0.labelc)
        self.group0.hbox2.addWidget(self.group0.linec)
        self.group0.hbox2.addWidget(self.group0.labeld)
        self.group0.hbox2.addWidget(self.group0.lined)
        self.group0.hbox3 = QHBoxLayout()
        self.group0.labelx = QLabel()
        self.group0.labelx.setText('Điểm trên Ox')
        self.group0.labelx.setMaximumWidth(70)
        self.group0.linex = QLineEdit()
        self.group0.linex.setText('-3,-2,-1,1,2,3')
        self.group0.linex.setMaximumWidth(70)
        self.group0.hbox3.addWidget(self.group0.labelx)
        self.group0.hbox3.addWidget(self.group0.linex)
        self.group0.hbox4 = QHBoxLayout()
        self.group0.labely = QLabel()
        self.group0.labely.setText('Điểm trên Oy')
        self.group0.labely.setMaximumWidth(70)
        self.group0.liney = QLineEdit()
        self.group0.liney.setText('-3,-2,-1,1,2,3')
        self.group0.liney.setMaximumWidth(70)
        self.group0.hbox4.addWidget(self.group0.labely)
        self.group0.hbox4.addWidget(self.group0.liney)
        self.group0.hbox5 = QHBoxLayout()
        self.group0.labels = QLabel()
        self.group0.labels.setText('Scale = ')
        self.group0.labels.setMaximumWidth(30)
        self.group0.lines = QLineEdit()
        self.group0.lines.setText('1')
        self.group0.lines.setMaximumWidth(20)
        self.group0.hbox5.addWidget(self.group0.labels)
        self.group0.hbox5.addWidget(self.group0.lines)
        self.group0.hbox.addLayout(self.group0.hbox1)
        self.group0.hbox.addLayout(self.group0.hbox2)
        self.group0.hbox.addLayout(self.group0.hbox3)
        self.group0.hbox.addLayout(self.group0.hbox4)
        self.group0.hbox.addLayout(self.group0.hbox5)
        self.group0.check2.setLayout(self.group0.hbox)
        self.group0.setLayout(self.group0.vbox)
        self.group0.vbox.addWidget(self.group0.check1)
        self.group0.vbox.addWidget(self.group0.check2)
        self.group0.setMaximumHeight(105)
        self.group1 = QGroupBox('Đồ thị hàm bậc nhất y = ax + b')
        self.group1.hbox = QHBoxLayout()
        self.group1.setLayout(self.group1.hbox)
        self.group1.labela = QLabel()
        self.group1.labela.setText('a = ')
        self.group1.labela.setMaximumWidth(20)
        self.group1.linea = QLineEdit()
        self.group1.linea.setText('1')
        self.group1.linea.setMaximumWidth(30)
        self.group1.labelb = QLabel()
        self.group1.labelb.setText('b = ')
        self.group1.labelb.setMaximumWidth(20)
        self.group1.lineb = QLineEdit()
        self.group1.lineb.setText('')
        self.group1.lineb.setMaximumWidth(30)
        button = QPushButton('Xuất code', self)
        button.clicked.connect(self.dothi_bac_nhat)
        self.group1.hbox.addWidget(self.group1.labela)
        self.group1.hbox.addWidget(self.group1.linea)
        self.group1.hbox.addWidget(self.group1.labelb)
        self.group1.hbox.addWidget(self.group1.lineb)
        self.group1.hbox.addWidget(button)
        self.layout().addWidget(self.group1, 2, 0)
        self.group2 = QGroupBox('Đồ thị hàm bậc hai y = ax^2 + bx + c')
        self.group2.hbox = QHBoxLayout()
        self.group2.setLayout(self.group2.hbox)
        self.group2.labela = QLabel()
        self.group2.labela.setText('a = ')
        self.group2.labela.setMaximumWidth(20)
        self.group2.linea = QLineEdit()
        self.group2.linea.setText('1')
        self.group2.linea.setMaximumWidth(30)
        self.group2.labelb = QLabel()
        self.group2.labelb.setText('b = ')
        self.group2.labelb.setMaximumWidth(20)
        self.group2.lineb = QLineEdit()
        self.group2.lineb.setText('')
        self.group2.lineb.setMaximumWidth(30)
        self.group2.labelc = QLabel()
        self.group2.labelc.setText('c = ')
        self.group2.labelc.setMaximumWidth(20)
        self.group2.linec = QLineEdit()
        self.group2.linec.setText('')
        self.group2.linec.setMaximumWidth(30)
        button = QPushButton('Xuất code', self)
        button.clicked.connect(self.dothi_bac_hai)
        self.group2.hbox.addWidget(self.group2.labela)
        self.group2.hbox.addWidget(self.group2.linea)
        self.group2.hbox.addWidget(self.group2.labelb)
        self.group2.hbox.addWidget(self.group2.lineb)
        self.group2.hbox.addWidget(self.group2.labelc)
        self.group2.hbox.addWidget(self.group2.linec)
        self.group2.hbox.addWidget(button)
        self.layout().addWidget(self.group2, 2, 1)
        self.group3 = QGroupBox('Đồ thị hàm bậc ba y = ax^3 + bx^2 + cx + d')
        self.group3.hbox = QHBoxLayout()
        self.group3.setLayout(self.group3.hbox)
        self.group3.labela = QLabel()
        self.group3.labela.setText('a = ')
        self.group3.labela.setMaximumWidth(20)
        self.group3.linea = QLineEdit()
        self.group3.linea.setText('1')
        self.group3.linea.setMaximumWidth(30)
        self.group3.labelb = QLabel()
        self.group3.labelb.setText('b = ')
        self.group3.labelb.setMaximumWidth(20)
        self.group3.lineb = QLineEdit()
        self.group3.lineb.setText('')
        self.group3.lineb.setMaximumWidth(30)
        self.group3.labelc = QLabel()
        self.group3.labelc.setText('c = ')
        self.group3.labelc.setMaximumWidth(20)
        self.group3.linec = QLineEdit()
        self.group3.linec.setText('')
        self.group3.linec.setMaximumWidth(30)
        self.group3.labeld = QLabel()
        self.group3.labeld.setText('d = ')
        self.group3.labeld.setMaximumWidth(20)
        self.group3.lined = QLineEdit()
        self.group3.lined.setText('')
        self.group3.lined.setMaximumWidth(30)
        button = QPushButton('Xuất code', self)
        button.clicked.connect(self.dothi_bac_ba)
        self.group3.hbox.addWidget(self.group3.labela)
        self.group3.hbox.addWidget(self.group3.linea)
        self.group3.hbox.addWidget(self.group3.labelb)
        self.group3.hbox.addWidget(self.group3.lineb)
        self.group3.hbox.addWidget(self.group3.labelc)
        self.group3.hbox.addWidget(self.group3.linec)
        self.group3.hbox.addWidget(self.group3.labeld)
        self.group3.hbox.addWidget(self.group3.lined)
        self.group3.hbox.addWidget(button)
        self.layout().addWidget(self.group3, 3, 0)
        self.group4 = QGroupBox('Đồ thị hàm trùng phương y = ax^4 + bx^2 + c')
        self.group4.hbox = QHBoxLayout()
        self.group4.setLayout(self.group4.hbox)
        self.group4.labela = QLabel()
        self.group4.labela.setText('a = ')
        self.group4.labela.setMaximumWidth(20)
        self.group4.linea = QLineEdit()
        self.group4.linea.setText('1')
        self.group4.linea.setMaximumWidth(30)
        self.group4.labelb = QLabel()
        self.group4.labelb.setText('b = ')
        self.group4.labelb.setMaximumWidth(20)
        self.group4.lineb = QLineEdit()
        self.group4.lineb.setText('')
        self.group4.lineb.setMaximumWidth(30)
        self.group4.labelc = QLabel()
        self.group4.labelc.setText('c = ')
        self.group4.labelc.setMaximumWidth(20)
        self.group4.linec = QLineEdit()
        self.group4.linec.setText('')
        self.group4.linec.setMaximumWidth(30)
        button = QPushButton('Xuất code', self)
        button.clicked.connect(self.dothi_bac_bon)
        self.group4.hbox.addWidget(self.group4.labela)
        self.group4.hbox.addWidget(self.group4.linea)
        self.group4.hbox.addWidget(self.group4.labelb)
        self.group4.hbox.addWidget(self.group4.lineb)
        self.group4.hbox.addWidget(self.group4.labelc)
        self.group4.hbox.addWidget(self.group4.linec)
        self.group4.hbox.addWidget(button)
        self.layout().addWidget(self.group4, 3, 1)
        self.group5 = QGroupBox('Đồ thị hàm phân thức y = \\dfrac{ax+b}{cx+d}')
        self.group5.grip = QGridLayout()
        self.group5.setLayout(self.group5.grip)
        self.group5.labela = QLabel()
        self.group5.labela.setText('a = ')
        self.group5.labela.setMaximumWidth(20)
        self.group5.linea = QLineEdit()
        self.group5.linea.setText('1')
        self.group5.linea.setMaximumWidth(30)
        self.group5.labelb = QLabel()
        self.group5.labelb.setText('b = ')
        self.group5.labelb.setMaximumWidth(20)
        self.group5.lineb = QLineEdit()
        self.group5.lineb.setText('')
        self.group5.lineb.setMaximumWidth(30)
        self.group5.labelc = QLabel()
        self.group5.labelc.setText('c = ')
        self.group5.labelc.setMaximumWidth(20)
        self.group5.linec = QLineEdit()
        self.group5.linec.setText('1')
        self.group5.linec.setMaximumWidth(30)
        self.group5.labeld = QLabel()
        self.group5.labeld.setText('d = ')
        self.group5.labeld.setMaximumWidth(20)
        self.group5.lined = QLineEdit()
        self.group5.lined.setText('')
        self.group5.lined.setMaximumWidth(30)
        button = QPushButton('Xuất code', self)
        button.clicked.connect(self.dothi_bac_mot_mot)
        self.group5.grip.addWidget(self.group5.labela, 1, 1)
        self.group5.grip.addWidget(self.group5.linea, 1, 2)
        self.group5.grip.addWidget(self.group5.labelb, 1, 3)
        self.group5.grip.addWidget(self.group5.lineb, 1, 4)
        self.group5.grip.addWidget(self.group5.labelc, 2, 1)
        self.group5.grip.addWidget(self.group5.linec, 2, 2)
        self.group5.grip.addWidget(self.group5.labeld, 2, 3)
        self.group5.grip.addWidget(self.group5.lined, 2, 4)
        self.group5.grip.addWidget(button, 2, 5)
        self.layout().addWidget(self.group5, 4, 0)
        self.group6 = QGroupBox('Đồ thị hàm phân thức y = \\dfrac{ax^2+bx+c}{mx+n}')
        self.group6.grip = QGridLayout()
        self.group6.setLayout(self.group6.grip)
        self.group6.labela = QLabel()
        self.group6.labela.setText('a = ')
        self.group6.labela.setMaximumWidth(20)
        self.group6.linea = QLineEdit()
        self.group6.linea.setText('1')
        self.group6.linea.setMaximumWidth(30)
        self.group6.labelb = QLabel()
        self.group6.labelb.setText('b = ')
        self.group6.labelb.setMaximumWidth(20)
        self.group6.lineb = QLineEdit()
        self.group6.lineb.setText('')
        self.group6.lineb.setMaximumWidth(30)
        self.group6.labelc = QLabel()
        self.group6.labelc.setText('c = ')
        self.group6.labelc.setMaximumWidth(20)
        self.group6.linec = QLineEdit()
        self.group6.linec.setText('')
        self.group6.linec.setMaximumWidth(30)
        self.group6.labelm = QLabel()
        self.group6.labelm.setText('m = ')
        self.group6.labelm.setMaximumWidth(20)
        self.group6.linem = QLineEdit()
        self.group6.linem.setText('1')
        self.group6.linem.setMaximumWidth(30)
        self.group6.labeln = QLabel()
        self.group6.labeln.setText('n = ')
        self.group6.labeln.setMaximumWidth(20)
        self.group6.linen = QLineEdit()
        self.group6.linen.setText('')
        self.group6.linen.setMaximumWidth(30)
        button = QPushButton('Xuất code', self)
        button.clicked.connect(self.dothi_bac_hai_mot)
        self.group6.grip.addWidget(self.group6.labela, 1, 1)
        self.group6.grip.addWidget(self.group6.linea, 1, 2)
        self.group6.grip.addWidget(self.group6.labelb, 1, 3)
        self.group6.grip.addWidget(self.group6.lineb, 1, 4)
        self.group6.grip.addWidget(self.group6.labelc, 1, 5)
        self.group6.grip.addWidget(self.group6.linec, 1, 6)
        self.group6.grip.addWidget(self.group6.labelm, 2, 3)
        self.group6.grip.addWidget(self.group6.linem, 2, 4)
        self.group6.grip.addWidget(self.group6.labeln, 2, 5)
        self.group6.grip.addWidget(self.group6.linen, 2, 6)
        self.group6.grip.addWidget(button, 2, 7)
        self.layout().addWidget(self.group6, 4, 1)
        self.group7 = QGroupBox('Đồ thị lượng giác y = a sin (bx)')
        self.group7.hbox = QHBoxLayout()
        self.group7.setLayout(self.group7.hbox)
        self.group7.labela = QLabel()
        self.group7.labela.setText('a = ')
        self.group7.labela.setMaximumWidth(20)
        self.group7.linea = QLineEdit()
        self.group7.linea.setText('1')
        self.group7.linea.setMaximumWidth(30)
        self.group7.labelb = QLabel()
        self.group7.labelb.setText('b = ')
        self.group7.labelb.setMaximumWidth(20)
        self.group7.lineb = QLineEdit()
        self.group7.lineb.setText('2')
        self.group7.lineb.setMaximumWidth(30)
        self.group7.labelc = QLabel()
        self.group7.labelc.setText('c = ')
        self.group7.labelc.setMaximumWidth(20)
        self.group7.linec = QLineEdit()
        self.group7.linec.setText('2')
        self.group7.linec.setMaximumWidth(30)
        button = QPushButton('Xuất code', self)
        button.clicked.connect(self.dothi_bac_hai_mot)
        self.group7.hbox.addWidget(self.group7.labela)
        self.group7.hbox.addWidget(self.group7.linea)
        self.group7.hbox.addWidget(self.group7.labelb)
        self.group7.hbox.addWidget(self.group7.lineb)
        self.group7.hbox.addWidget(self.group7.labelc)
        self.group7.hbox.addWidget(self.group7.linec)
        self.group7.hbox.addWidget(button)
        self.group8 = QGroupBox('Đồ thị hàm bậc hai y = ax^2 + bx + c')
        self.group8.hbox = QHBoxLayout()
        self.group8.setLayout(self.group8.hbox)
        self.group8.labela = QLabel()
        self.group8.labela.setText('a = ')
        self.group8.labela.setMaximumWidth(20)
        self.group8.linea = QLineEdit()
        self.group8.linea.setText('1')
        self.group8.linea.setMaximumWidth(30)
        self.group8.labelb = QLabel()
        self.group8.labelb.setText('b = ')
        self.group8.labelb.setMaximumWidth(20)
        self.group8.lineb = QLineEdit()
        self.group8.lineb.setText('2')
        self.group8.lineb.setMaximumWidth(30)
        self.group8.labelc = QLabel()
        self.group8.labelc.setText('c = ')
        self.group8.labelc.setMaximumWidth(20)
        self.group8.linec = QLineEdit()
        self.group8.linec.setText('2')
        self.group8.linec.setMaximumWidth(30)
        button = QPushButton('Xuất code', self)
        button.clicked.connect(self.dothi_bac_nhat)
        self.group8.hbox.addWidget(self.group8.labela)
        self.group8.hbox.addWidget(self.group8.linea)
        self.group8.hbox.addWidget(self.group8.labelb)
        self.group8.hbox.addWidget(self.group8.lineb)
        self.group8.hbox.addWidget(self.group8.labelc)
        self.group8.hbox.addWidget(self.group8.linec)
        self.group8.hbox.addWidget(button)
        for group in (self.group1, self.group2, self.group3, self.group4, self.group7, self.group8):
            group.setMaximumHeight(65)

        for group in (self.group5, self.group6):
            group.setMaximumHeight(90)

        self.code = QGroupBox('Code')
        self.code.vbox = QVBoxLayout()
        self.code.setLayout(self.code.vbox)
        self.code.label = QLabel()
        self.code.vbox.addWidget(self.code.label)
        self.copy = QHBoxLayout()
        self.copy1 = QPushButton('Copy (Code Tikz)', self)
        self.copy1.clicked.connect(self.Copy_Code_Tikz)
        self.copy2 = QPushButton('Copy All (book)', self)
        self.copy2.clicked.connect(self.Copy_Full_Tikz)
        self.copy.addWidget(self.copy1)
        self.copy.addWidget(self.copy2)
        self.run = QHBoxLayout()
        self.run1 = QPushButton('PdfLaTeX (book)', self)
        self.run1.clicked.connect(self.Pdflatex_Full_Tikz)
        self.run2 = QPushButton('PdfLaTeX (standalone)', self)
        self.run2.clicked.connect(self.Pdflatex_Copy_Tikz)
        self.run.addWidget(self.run1)
        self.run.addWidget(self.run2)
        self.layout().addWidget(self.code, 6, 0, 1, 2)
        self.layout().addLayout(self.copy, 7, 0)
        self.layout().addLayout(self.run, 7, 1)
        for widget in (self.group1, self.group2, self.group3, self.group4, self.group5, self.group6):
            widget.setMinimumHeight(60)
            widget.setMaximumHeight(60)

        for widget in (self.group5, self.group6):
            widget.setMinimumHeight(90)
            widget.setMaximumHeight(90)

    def Manual_Check(self):
        if self.group0.check2.isChecked():
            self.group0.check1.setChecked(False)
        else:
            self.group0.check1.setChecked(True)

    def Auto_Check(self):
        if self.group0.check1.isChecked():
            self.group0.check2.setChecked(False)
        else:
            self.group0.check2.setChecked(True)

    def dothi_bac_nhat(self):
        try:
            a = get_number_diag(self.group1.linea.text())
            b = get_number_diag(self.group1.lineb.text())
            block = 'Đồ thị của hàm số $y=' + view_dt_bac_nhat((float(a)), (float(b)), x='x') + '$.\n\n'
            block += dothi_bac_nhat_source(a, b, '', '', '')
            self.code.label.setText(block)
        except ValueError as error:
            TB_Error_Input(self, str(error))

    def dothi_bac_hai(self):
        try:
            a = get_number_diag(self.group2.linea.text())
            b = get_number_diag(self.group2.lineb.text())
            c = get_number_diag(self.group2.linec.text())
            block = 'Đồ thị của hàm số $y=' + view_dt_bac_hai(a, b, c, x='x') + '$.\n\n'
            block += dothi_bac_hai_source(a, b, c, '', '', '')
            self.code.label.setText(block)
        except ValueError as error:
            TB_Error_Input(self, str(error))

    def dothi_bac_ba(self):
        try:
            a = get_number_diag(self.group3.linea.text())
            b = get_number_diag(self.group3.lineb.text())
            c = get_number_diag(self.group3.linec.text())
            d = get_number_diag(self.group3.lined.text())
            block = 'Đồ thị của hàm số $y=' + view_dt_bac_ba(a, b, c, d, x='x') + '$.\n\n'
            block += dothi_bac_ba_source(a, b, c, d, '', '', '')
            self.code.label.setText(block)
        except ValueError as error:
            TB_Error_Input(self, str(error))

    def dothi_bac_bon(self):
        try:
            a = get_number_diag(self.group4.linea.text())
            b = get_number_diag(self.group4.lineb.text())
            c = get_number_diag(self.group4.linec.text())
            block = 'Đồ thị của hàm số $y=' + view_dt_bac_bon(a, 0, b, 0, c, x='x') + '$.\n\n'
            block += dothi_trung_phuong_source(a, b, c, '', '', '')
            self.code.label.setText(block)
        except ValueError as error:
            TB_Error_Input(self, str(error))

    def dothi_bac_mot_mot(self):
        try:
            a = get_number_diag(self.group5.linea.text())
            b = get_number_diag(self.group5.lineb.text())
            c = get_number_diag(self.group5.linec.text())
            d = get_number_diag(self.group5.lined.text())
            block = 'Đồ thị của hàm số $y=\\dfrac{' + view_dt_bac_nhat(a, b, x='x') + '}{' + view_dt_bac_nhat(c, d, x='x') + '}$.\n\n'
            block += dothi_bac_mot_mot_source(a, b, c, d, '', '', '')
            self.code.label.setText(block)
        except ValueError as error:
            TB_Error_Input(self, str(error))

    def dothi_bac_hai_mot(self):
        try:
            a = get_number_diag(self.group6.linea.text())
            b = get_number_diag(self.group6.lineb.text())
            c = get_number_diag(self.group6.linec.text())
            m = get_number_diag(self.group6.linem.text())
            n = get_number_diag(self.group6.linen.text())
            block = 'Đồ thị của hàm số $y=\\dfrac{' + view_dt_bac_hai(a, b, c, x='x') + '}{' + view_dt_bac_nhat(m, n, x='x') + '}$.\n\n'
            block += dothi_bac_hai_mot_source(a, b, c, m, n, '', '', '')
            self.code.label.setText(block)
        except ValueError as error:
            TB_Error_Input(self, str(error))

    def Copy_Code(self):
        text = self.code.label.text()
        QApplication.clipboard().setText(text)

    def Copy_Code_Tikz(self):
        try:
            text1 = self.code.label.text()
            s = text1.index('\n\n')
            text = text1[s + 2:]
            QApplication.clipboard().setText(text)
        except Exception as err:
            QApplication.clipboard().setText('')

    def Copy_Full_Tikz(self):
        text1 = self.code.label.text()
        text = '\\documentclass{book}\n\\usepackage[utf8]{vietnam}\n\\usepackage{amsmath}\n\\usepackage{tkz-tab}\n\\begin{document}\n' + text1 + '\n\\end{document}'
        QApplication.clipboard().setText(text)

    def Copy_Pdf_Tikz(self):
        text1 = self.code.label.text()
        text = '\\documentclass{standalone}\n\\usepackage{amsmath}\n\\usepackage{tkz-tab}\n\\begin{document}\n' + text1 + '\n\\end{document}'
        QApplication.clipboard().setText(text)

    def Pdflatex_Full_Tikz(self):
        text1 = self.code.label.text()
        text = '\\documentclass{book}\n\\usepackage[utf8]{vietnam}\n\\usepackage{amsmath}\n\\usepackage{tkz-tab}\n\\begin{document}\n' + text1 + '\n\\end{document}'
        now = datetime.now()
        tenfile = 'DT_book_' + str(now.year) + '-' + str(now.month) + '-' + str(now.day) + '-' + str(now.hour) + '-' + str(now.minute) + '-' + str(now.second)
        PdfLaTeX('DOTHI', tenfile, text)
        path='DOTHI\\' + tenfile + '.pdf'
        if openfile(path)=='Error':
            QMessageBox.critical(self, 'Lỗi','Lỗi mở file '+path)

    def Pdflatex_Copy_Tikz(self):
        try:
            text1 = self.code.label.text()
            s = text1.index('\n\n')
            text2 = text1[s + 2:]
            text = '\\documentclass{standalone}\n\\usepackage{tikz,tkz-euclide}\n\\usepackage{amsmath}\n\\begin{document}\n' + text2 + '\\end{document}'
            now = datetime.now()
            tenfile = 'BBT_standalone_' + str(now.year) + '-' + str(now.month) + '-' + str(now.day) + '-' + str(now.hour) + '-' + str(now.minute) + '-' + str(now.second)
            PdfLaTeX('BBT', tenfile, text)
            path='BBT\\' + tenfile + '.pdf'
            if openfile(path)=='Error':
                QMessageBox.critical(self, 'Lỗi','Lỗi mở file '+path)
        except ValueError as err:
            TB_Error_PdfLaTeX(self, str(err))